version: '3'
services:
    cf_builder:
        build: ./dockerfile/builder
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
    cf_client:
        build: ./dockerfile/client
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/bus/usb:/dev/bus/usb
            - ./dockerfile/.env:/.env
            - /dev/pts:/dev/pts
        privileged: true
        environment:
            DISPLAY: unix:0
        entrypoint: cfclient
    cf_agent:
        build: ./dockerfile/agent
        volumes:
            - /dev/pts:/dev/pts
        env_file:
            - ./dockerfile/.env/variables.env
        network_mode: "host"
        depends_on:
            - cf_client
    cf_rviz:
        build: ./dockerfile/rviz
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        environment:
            DISPLAY: unix:0
        network_mode: "host"